export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED';
export const FETCH_POSTS = 'FETCH_POSTS';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const NEW_POST_CREATED = 'NEW_POST_CREATED';
export const GET_POST = 'GET_POST';
export const POST_DETAILS_RECEIVED = 'POST_DETAILS_RECEIVED';